### ISSUE TITLE
[Feature Request] Add option to keep cursor in-place

### ISSUE THREAD

**Issue by ColinKennedy** [rasulomaroff/telepath.nvim#1]
This plugin really shines when working with splits but if you are using it to jump within the same buffer and the jump results in a scroll movement, it can be a bit disorienting for the cursor to leap to a location and then restore back because the scroll position keeps changing

https://github.com/rasulomaroff/telepath.nvim/assets/10103049/dc3d2d5f-1014-407c-993d-6ef586f5396f

Could there be an option to prevent cursor movement? e.g. you can still leap but your cursor doesn't visibly move to the location (and so the cursor wouldn't need to be restored, either)

**Comment by rasulomaroff** [comment]
Hi there! @ColinKennedy 

Since you have to perform an operator on a text object, you literally need to be in that specific location to be able to do that.

The way I could potentially address this issue is by restoring the same window position you had before jumping anywhere, because right now you lose your scroll position. Does that sound okay for you?

**Comment by ColinKennedy** [comment]
Yeah that sounds great! And yep, you're right, because you're using text objects that you can't exactly fake it. But as long as the latency  (of the text object, not telepath.nvim) is low enough I think the solution you've described should be able to work well!

**Comment by rasulomaroff** [comment]
@ColinKennedy just pushed the changes. I made this behaviour the default, because it should've been like that. Thank you for opening the issue!
